#!/usr/bin/env python3
# Copyright 2024 The Kubric Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pack MOVi raw sample directories into sharded training/distribution formats.

The raw MOVi layout generated by the workers is convenient for generation and
inspection, but it creates many small files and directories. This module keeps
that raw layout intact and builds a separate sharded representation for
cross-machine distribution and high-throughput sequential reads.

Supported shard formats:
  - webdataset: uncompressed tar shards containing one manifest and one
    lossless payload tar per sample.
  - tfrecord: uncompressed TFRecord shards containing the same manifest and
    payload bytes per sample.
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import io
import json
import tarfile
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Sequence, Tuple, TypeVar

try:
  import tensorflow as tf
except ImportError:  # pragma: no cover
  tf = None


SUPPORTED_FORMATS = ("webdataset", "tfrecord", "both")
REQUIRED_SAMPLE_FILES = ("metadata.json", "events.json", "point_cloud_states.pkl")
T = TypeVar("T")


@dataclasses.dataclass(frozen=True)
class SamplePayload:
  """Lossless serialized representation of one raw sample directory."""

  sample_id: str
  payload_bytes: bytes
  payload_sha256: str
  source_total_bytes: int
  file_entries: List[Dict[str, object]]


def _utc_now() -> str:
  return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def _format_bytes(num_bytes: int) -> str:
  if num_bytes < 1024:
    return f"{num_bytes} B"
  units = ("KiB", "MiB", "GiB", "TiB")
  value = float(num_bytes)
  for unit in units:
    value /= 1024.0
    if value < 1024.0 or unit == units[-1]:
      return f"{value:.1f} {unit}"
  return f"{value:.1f} TiB"


def _format_duration(seconds: float) -> str:
  total_seconds = max(0, int(seconds))
  hours, remainder = divmod(total_seconds, 3600)
  minutes, secs = divmod(remainder, 60)
  if hours > 0:
    return f"{hours:d}:{minutes:02d}:{secs:02d}"
  return f"{minutes:02d}:{secs:02d}"


def _print_progress(message: str) -> None:
  print(message, flush=True)


def _iter_sample_dirs(source_root: Path) -> Iterator[Path]:
  for child in sorted(source_root.iterdir()):
    if not child.is_dir():
      continue
    if child.name.startswith("_") or child.name in ("logs", "status"):
      continue
    if _is_complete_sample_dir(child):
      yield child


def _is_complete_sample_dir(sample_dir: Path) -> bool:
  filenames = {path.name for path in sample_dir.iterdir() if path.is_file()}
  if not all(name in filenames for name in REQUIRED_SAMPLE_FILES):
    return False
  return any(name.startswith("rgba_") for name in filenames)


def _build_sample_payload(sample_dir: Path) -> SamplePayload:
  file_paths = sorted(path for path in sample_dir.rglob("*") if path.is_file())
  total_size = 0
  file_entries = []
  payload_buffer = io.BytesIO()

  with tarfile.open(fileobj=payload_buffer, mode="w") as payload_tar:
    for path in file_paths:
      rel_path = path.relative_to(sample_dir).as_posix()
      stat = path.stat()
      total_size += stat.st_size
      file_entries.append({
          "name": rel_path,
          "size": stat.st_size,
      })
      tar_info = payload_tar.gettarinfo(str(path), arcname=rel_path)
      with path.open("rb") as fp:
        payload_tar.addfile(tar_info, fp)

  payload_bytes = payload_buffer.getvalue()
  payload_sha256 = hashlib.sha256(payload_bytes).hexdigest()
  return SamplePayload(
      sample_id=sample_dir.name,
      payload_bytes=payload_bytes,
      payload_sha256=payload_sha256,
      source_total_bytes=total_size,
      file_entries=file_entries,
  )


def _build_sample_manifest(sample_dir: Path,
                           payload: SamplePayload,
                           shard_index: int,
                           shard_relpath: str,
                           output_format: str) -> Dict[str, object]:
  return {
      "sample_id": sample_dir.name,
      "source_dir": sample_dir.name,
      "format": output_format,
      "shard_index": shard_index,
      "shard_path": shard_relpath,
      "num_files": len(payload.file_entries),
      "source_total_bytes": payload.source_total_bytes,
      "payload_tar_bytes": len(payload.payload_bytes),
      "payload_sha256": payload.payload_sha256,
      "files": payload.file_entries,
  }


def _write_json(path: Path, data: object) -> None:
  path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n",
                  encoding="utf-8")


def _add_bytes_to_tar(tar: tarfile.TarFile, arcname: str, data: bytes) -> None:
  info = tarfile.TarInfo(name=arcname)
  info.size = len(data)
  info.mtime = int(datetime.now().timestamp())
  tar.addfile(info, io.BytesIO(data))


def _write_webdataset_shard(
    shard_path: Path,
    samples: Sequence[Tuple[Path, SamplePayload]],
    shard_index: int,
) -> Tuple[List[Dict[str, object]], Dict[str, object]]:
  sample_records = []
  total_payload_bytes = 0
  tmp_path = shard_path.with_suffix(shard_path.suffix + ".tmp")

  with tarfile.open(tmp_path, mode="w") as shard_tar:
    for sample_dir, payload in samples:
      total_payload_bytes += len(payload.payload_bytes)
      manifest = _build_sample_manifest(
          sample_dir=sample_dir,
          payload=payload,
          shard_index=shard_index,
          shard_relpath=shard_path.name,
          output_format="webdataset",
      )
      sample_records.append(manifest)
      _add_bytes_to_tar(
          shard_tar,
          arcname=f"{payload.sample_id}.manifest.json",
          data=json.dumps(manifest, sort_keys=True).encode("utf-8"),
      )
      _add_bytes_to_tar(
          shard_tar,
          arcname=f"{payload.sample_id}.payload.tar",
          data=payload.payload_bytes,
      )

  tmp_path.replace(shard_path)
  shard_record = {
      "shard_index": shard_index,
      "path": shard_path.name,
      "num_samples": len(samples),
      "payload_bytes": total_payload_bytes,
      "format": "webdataset",
  }
  return sample_records, shard_record


def _bytes_feature(value: bytes):
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def _int64_feature(value: int):
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def _write_tfrecord_shard(
    shard_path: Path,
    samples: Sequence[Tuple[Path, SamplePayload]],
    shard_index: int,
) -> Tuple[List[Dict[str, object]], Dict[str, object]]:
  if tf is None:  # pragma: no cover
    raise ImportError("tensorflow is required to write TFRecord shards.")

  sample_records = []
  total_payload_bytes = 0
  tmp_path = shard_path.with_suffix(shard_path.suffix + ".tmp")

  with tf.io.TFRecordWriter(str(tmp_path)) as writer:
    for sample_dir, payload in samples:
      total_payload_bytes += len(payload.payload_bytes)
      manifest = _build_sample_manifest(
          sample_dir=sample_dir,
          payload=payload,
          shard_index=shard_index,
          shard_relpath=shard_path.name,
          output_format="tfrecord",
      )
      sample_records.append(manifest)
      example = tf.train.Example(features=tf.train.Features(feature={
          "sample_id": _bytes_feature(payload.sample_id.encode("utf-8")),
          "manifest_json": _bytes_feature(
              json.dumps(manifest, sort_keys=True).encode("utf-8")),
          "payload_tar": _bytes_feature(payload.payload_bytes),
          "payload_num_bytes": _int64_feature(len(payload.payload_bytes)),
      }))
      writer.write(example.SerializeToString())

  tmp_path.replace(shard_path)
  shard_record = {
      "shard_index": shard_index,
      "path": shard_path.name,
      "num_samples": len(samples),
      "payload_bytes": total_payload_bytes,
      "format": "tfrecord",
  }
  return sample_records, shard_record


def _chunked(items: Sequence[T], chunk_size: int) -> Iterator[Sequence[T]]:
  for start in range(0, len(items), chunk_size):
    yield items[start:start + chunk_size]


def pack_dataset(source_root: Path,
                 output_root: Path,
                 output_format: str,
                 shard_size: int,
                 max_samples: Optional[int] = None,
                 progress_every: int = 25) -> Dict[str, Path]:
  if output_format not in SUPPORTED_FORMATS:
    raise ValueError(f"Unsupported format {output_format!r}.")
  if shard_size <= 0:
    raise ValueError("shard_size must be positive.")
  if progress_every <= 0:
    raise ValueError("progress_every must be positive.")
  if output_format in ("tfrecord", "both") and tf is None:
    raise ImportError(
        "tensorflow is required for TFRecord export. "
        "Install tensorflow or use --format webdataset.")

  _print_progress(f"[scan] scanning sample directories under {source_root}")
  sample_dirs = list(_iter_sample_dirs(source_root))
  if max_samples is not None:
    sample_dirs = sample_dirs[:max_samples]
  if not sample_dirs:
    raise ValueError(f"No complete MOVi sample directories found in {source_root}.")
  total_samples = len(sample_dirs)
  total_shards = (total_samples + shard_size - 1) // shard_size
  _print_progress(
      f"[scan] found {total_samples} complete samples; "
      f"target format={output_format} shard_size={shard_size} num_shards={total_shards}")

  formats = ("webdataset", "tfrecord") if output_format == "both" else (output_format,)
  sample_payloads = []
  serialize_start = time.perf_counter()
  serialized_source_bytes = 0
  serialized_payload_bytes = 0
  for index, sample_dir in enumerate(sample_dirs, start=1):
    payload = _build_sample_payload(sample_dir)
    sample_payloads.append((sample_dir, payload))
    serialized_source_bytes += payload.source_total_bytes
    serialized_payload_bytes += len(payload.payload_bytes)
    if index == 1 or index % progress_every == 0 or index == total_samples:
      elapsed = time.perf_counter() - serialize_start
      rate = index / elapsed if elapsed > 0 else 0.0
      eta = (total_samples - index) / rate if rate > 0 else 0.0
      _print_progress(
          f"[pack] samples {index}/{total_samples} "
          f"({100.0 * index / total_samples:.1f}%) "
          f"last={sample_dir.name} "
          f"source={_format_bytes(serialized_source_bytes)} "
          f"payload={_format_bytes(serialized_payload_bytes)} "
          f"rate={rate:.2f} samples/s eta={_format_duration(eta)}")

  written_roots = {}
  for fmt in formats:
    format_root = output_root / fmt
    shards_root = format_root / "shards"
    shards_root.mkdir(parents=True, exist_ok=True)
    sample_manifest_path = format_root / "manifest.jsonl"

    all_sample_records = []
    shard_records = []
    format_start = time.perf_counter()
    written_samples = 0
    for shard_index, chunk in enumerate(_chunked(sample_payloads, shard_size)):
      suffix = ".tar" if fmt == "webdataset" else ".tfrecord"
      shard_path = shards_root / f"shard-{shard_index:06d}{suffix}"
      chunk_start_sample = written_samples + 1
      chunk_end_sample = written_samples + len(chunk)
      _print_progress(
          f"[write:{fmt}] shard {shard_index + 1}/{total_shards} "
          f"samples {chunk_start_sample}-{chunk_end_sample} -> {shard_path.name}")
      if fmt == "webdataset":
        sample_records, shard_record = _write_webdataset_shard(
            shard_path=shard_path, samples=chunk, shard_index=shard_index)
      else:
        sample_records, shard_record = _write_tfrecord_shard(
            shard_path=shard_path, samples=chunk, shard_index=shard_index)
      all_sample_records.extend(sample_records)
      shard_records.append(shard_record)
      written_samples += len(chunk)
      elapsed = time.perf_counter() - format_start
      rate = written_samples / elapsed if elapsed > 0 else 0.0
      eta = (total_samples - written_samples) / rate if rate > 0 else 0.0
      _print_progress(
          f"[write:{fmt}] done shard {shard_index + 1}/{total_shards} "
          f"written_samples={written_samples}/{total_samples} "
          f"({100.0 * written_samples / total_samples:.1f}%) "
          f"rate={rate:.2f} samples/s eta={_format_duration(eta)}")

    with sample_manifest_path.open("w", encoding="utf-8") as fp:
      for record in all_sample_records:
        fp.write(json.dumps(record, sort_keys=True) + "\n")

    dataset_manifest = {
        "created_at_utc": _utc_now(),
        "format": fmt,
        "source_root": str(source_root.resolve()),
        "output_root": str(format_root.resolve()),
        "shard_size": shard_size,
        "num_samples": len(sample_dirs),
        "num_shards": len(shard_records),
        "sample_manifest": sample_manifest_path.name,
        "required_sample_files": list(REQUIRED_SAMPLE_FILES),
        "shards": shard_records,
    }
    _write_json(format_root / "dataset_manifest.json", dataset_manifest)
    written_roots[fmt] = format_root
    _print_progress(
        f"[done:{fmt}] wrote {len(shard_records)} shards and {len(all_sample_records)} samples to {format_root}")

  return written_roots


def unpack_payload_tar(payload_bytes: bytes) -> Dict[str, bytes]:
  """Return a mapping of relative filenames to raw bytes for one sample."""
  files = {}
  with tarfile.open(fileobj=io.BytesIO(payload_bytes), mode="r:") as payload_tar:
    for member in payload_tar.getmembers():
      if not member.isfile():
        continue
      extracted = payload_tar.extractfile(member)
      if extracted is None:
        continue
      files[member.name] = extracted.read()
  return files


def iter_webdataset_records(shard_path: Path) -> Iterator[Dict[str, object]]:
  """Iterate records from one webdataset shard created by this module."""
  grouped = {}
  with tarfile.open(shard_path, mode="r:") as shard_tar:
    for member in shard_tar.getmembers():
      if not member.isfile():
        continue
      extracted = shard_tar.extractfile(member)
      if extracted is None:
        continue
      stem, suffix = member.name.rsplit(".", 1)
      key, field = stem.split(".", 1)
      grouped.setdefault(key, {})[field + "." + suffix] = extracted.read()

  for sample_id in sorted(grouped):
    fields = grouped[sample_id]
    manifest = json.loads(fields["manifest.json"].decode("utf-8"))
    yield {
        "sample_id": sample_id,
        "manifest": manifest,
        "payload_tar": fields["payload.tar"],
    }


def iter_tfrecord_records(shard_path: Path) -> Iterator[Dict[str, object]]:
  """Iterate records from one TFRecord shard created by this module."""
  if tf is None:  # pragma: no cover
    raise ImportError("tensorflow is required to read TFRecord shards.")

  description = {
      "sample_id": tf.io.FixedLenFeature([], tf.string),
      "manifest_json": tf.io.FixedLenFeature([], tf.string),
      "payload_tar": tf.io.FixedLenFeature([], tf.string),
      "payload_num_bytes": tf.io.FixedLenFeature([], tf.int64),
  }
  dataset = tf.data.TFRecordDataset([str(shard_path)])
  for raw_record in dataset:
    parsed = tf.io.parse_single_example(raw_record, description)
    sample_id = parsed["sample_id"].numpy().decode("utf-8")
    manifest = json.loads(parsed["manifest_json"].numpy().decode("utf-8"))
    yield {
        "sample_id": sample_id,
        "manifest": manifest,
        "payload_tar": parsed["payload_tar"].numpy(),
    }


def build_argparser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(
      description="Pack MOVi raw sample directories into shard datasets.")
  parser.add_argument(
      "--source-root",
      required=True,
      type=Path,
      help="Raw MOVi directory containing one subdirectory per sample.")
  parser.add_argument(
      "--output-root",
      required=True,
      type=Path,
      help="Destination root. Format-specific outputs are written below it.")
  parser.add_argument(
      "--format",
      dest="output_format",
      default="webdataset",
      choices=SUPPORTED_FORMATS,
      help="Shard format to create. Use 'both' to create both outputs.")
  parser.add_argument(
      "--shard-size",
      default=1000,
      type=int,
      help="Number of samples per shard.")
  parser.add_argument(
      "--max-samples",
      default=None,
      type=int,
      help="Optional limit for debugging or incremental conversion.")
  parser.add_argument(
      "--progress-every",
      default=25,
      type=int,
      help="Print packing progress every N serialized samples.")
  return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
  args = build_argparser().parse_args(argv)
  written_roots = pack_dataset(
      source_root=args.source_root,
      output_root=args.output_root,
      output_format=args.output_format,
      shard_size=args.shard_size,
      max_samples=args.max_samples,
      progress_every=args.progress_every,
  )
  for fmt, path in sorted(written_roots.items()):
    print(f"[{fmt}] wrote shards to {path}")
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
