#!/usr/bin/env python3
# Copyright 2024 The Kubric Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Visualize point-cloud states exported by challenges/movi/movi_ab_worker.py."""

import argparse
import json
import pathlib
import pickle

import numpy as np
from PIL import Image
from PIL import ImageColor
from PIL import ImageDraw
from PIL import ImageFont


POINT_STATE_FILENAME = "point_cloud_states.pkl"
RGBA_TEMPLATE = "rgba_{:05d}.png"
SEGMENTATION_TEMPLATE = "segmentation_{:05d}.png"
DEPTH_TEMPLATE = "depth_{:05d}.tiff"
POINT_KIND_VOLUME = 0
POINT_KIND_SURFACE = 1
DEFAULT_COLORS = (
    "#e63946",
    "#457b9d",
    "#2a9d8f",
    "#f4a261",
    "#8d99ae",
    "#ef476f",
    "#118ab2",
    "#06d6a0",
    "#ffd166",
    "#8338ec",
    "#fb5607",
    "#3a86ff",
)


def parse_args():
  parser = argparse.ArgumentParser(
      description="Visualize point-cloud states generated by movi_ab_worker.py.")
  parser.add_argument(
      "--input_dir",
      type=pathlib.Path,
      required=True,
      help="Directory produced by movi_ab_worker.py.")
  parser.add_argument(
      "--output_dir",
      type=pathlib.Path,
      default=None,
      help="Directory to write visualization outputs to. "
           "Defaults to <input_dir>/point_state_viz.")
  parser.add_argument(
      "--max_points_per_object",
      type=int,
      default=64,
      help="Maximum number of sampled points per object to draw.")
  parser.add_argument(
      "--frame_stride",
      type=int,
      default=1,
      help="Render every N-th frame.")
  parser.add_argument(
      "--point_radius",
      type=int,
      default=2,
      help="Rendered radius of each point.")
  parser.add_argument(
      "--world_view_size",
      type=int,
      default=320,
      help="Size of the bird's-eye and side-view panels.")
  parser.add_argument(
      "--velocity_scale",
      type=float,
      default=0.25,
      help="Arrow scale in seconds for velocity visualization.")
  parser.add_argument(
      "--gif_name",
      type=str,
      default="point_cloud_states.gif",
      help="Filename of the animated GIF.")
  parser.add_argument(
      "--skip_gif",
      action="store_true",
      help="Only write frame PNGs and summary text.")
  parser.add_argument(
      "--skip_3d_export",
      action="store_true",
      help="Do not export per-frame 3D point clouds and meshes.")
  parser.add_argument(
      "--depth_tolerance_abs",
      type=float,
      default=0.05,
      help="Absolute depth tolerance in meters for visible-point filtering.")
  parser.add_argument(
      "--depth_tolerance_rel",
      type=float,
      default=0.01,
      help="Relative depth tolerance for visible-point filtering.")
  parser.add_argument(
      "--visibility_radius",
      type=int,
      default=1,
      help="Pixel radius used when matching segmentation/depth visibility.")
  return parser.parse_args()


def _load_json(path):
  with path.open("r", encoding="utf-8") as fp:
    return json.load(fp)


def _load_pickle(path):
  with path.open("rb") as fp:
    return pickle.load(fp)


def _require_file(path, message):
  if not path.exists():
    raise FileNotFoundError(message)


def _resolve_output_dir(args):
  if args.output_dir is not None:
    return args.output_dir
  return args.input_dir / "point_state_viz"


def _find_point_state_path(input_dir, metadata):
  point_state_summary = metadata.get("point_cloud_states", {})
  filename = point_state_summary.get("filename", POINT_STATE_FILENAME)
  point_state_path = input_dir / filename
  _require_file(
      point_state_path,
      f"Missing {point_state_path}. "
      "Run movi_ab_worker.py with point sampling enabled first.")
  return point_state_path


def _get_palette(num_instances):
  palette = []
  for index in range(num_instances):
    palette.append(ImageColor.getrgb(DEFAULT_COLORS[index % len(DEFAULT_COLORS)]))
  return palette


def _quaternions_to_rotation_matrices(quaternions):
  quaternions = np.asarray(quaternions, dtype=np.float32)
  quaternions = quaternions / np.clip(
      np.linalg.norm(quaternions, axis=-1, keepdims=True), a_min=1e-8, a_max=None)
  w = quaternions[:, 0]
  x = quaternions[:, 1]
  y = quaternions[:, 2]
  z = quaternions[:, 3]
  return np.stack([
      1. - 2. * (y * y + z * z),
      2. * (x * y - z * w),
      2. * (x * z + y * w),
      2. * (x * y + z * w),
      1. - 2. * (x * x + z * z),
      2. * (y * z - x * w),
      2. * (x * z - y * w),
      2. * (y * z + x * w),
      1. - 2. * (x * x + y * y),
  ], axis=-1).reshape((-1, 3, 3)).astype(np.float32)


def _camera_matrix_world(position, quaternion):
  matrix = np.eye(4, dtype=np.float32)
  matrix[:3, :3] = _quaternions_to_rotation_matrices(
      np.asarray(quaternion, dtype=np.float32)[None, :])[0]
  matrix[:3, 3] = np.asarray(position, dtype=np.float32)
  return matrix


def _project_points(points, camera_position, camera_quaternion, intrinsics):
  matrix_world = _camera_matrix_world(camera_position, camera_quaternion)
  homo_transform = np.linalg.inv(matrix_world)
  homo_intrinsics = np.zeros((3, 4), dtype=np.float32)
  homo_intrinsics[:, :3] = intrinsics
  point4d = np.concatenate(
      [np.asarray(points, dtype=np.float32), np.ones((len(points), 1), dtype=np.float32)],
      axis=1)
  projected = (homo_intrinsics @ homo_transform @ point4d.T).T
  image_coords = projected[:, :2] / projected[:, 2:3]
  depth_sign = np.sign(projected[:, 2])
  return image_coords, depth_sign


def _normalized_to_pixel(coords, image_size):
  width, height = image_size
  x = np.clip(np.floor(coords[:, 0] * width), 0, width - 1).astype(np.int32)
  y = np.clip(np.floor(coords[:, 1] * height), 0, height - 1).astype(np.int32)
  return np.stack([x, y], axis=-1)


def _load_rgba_image(input_dir, frame_id, resolution):
  rgba_path = input_dir / RGBA_TEMPLATE.format(frame_id)
  if rgba_path.exists():
    return Image.open(rgba_path).convert("RGBA")
  width = int(resolution[1])
  height = int(resolution[0])
  return Image.new("RGBA", (width, height), (255, 255, 255, 255))


def _load_segmentation_image(input_dir, frame_id):
  segmentation_path = input_dir / SEGMENTATION_TEMPLATE.format(frame_id)
  _require_file(segmentation_path, f"Missing {segmentation_path}.")
  return np.array(Image.open(segmentation_path), dtype=np.int32)


def _load_depth_image(input_dir, frame_id):
  depth_path = input_dir / DEPTH_TEMPLATE.format(frame_id)
  _require_file(depth_path, f"Missing {depth_path}.")
  return np.array(Image.open(depth_path), dtype=np.float32)


def _make_subset_indices(start, end, max_points):
  num_points = end - start
  if max_points <= 0 or num_points <= max_points:
    return np.arange(start, end, dtype=np.int32)
  relative = np.linspace(0, num_points - 1, num=max_points, dtype=np.int32)
  return start + relative


def _subset_existing_indices(indices, max_points):
  indices = np.asarray(indices, dtype=np.int32)
  if max_points <= 0 or len(indices) <= max_points:
    return indices
  relative = np.linspace(0, len(indices) - 1, num=max_points, dtype=np.int32)
  return indices[relative]


def _get_point_kinds(point_payload, expected_num_points):
  point_kinds = point_payload.get("point_kinds")
  if point_kinds is None:
    return np.full((expected_num_points,), POINT_KIND_VOLUME, dtype=np.uint8)
  point_kinds = np.asarray(point_kinds, dtype=np.uint8)
  if point_kinds.shape != (expected_num_points,):
    raise ValueError(
        f"Expected point_kinds with shape ({expected_num_points},), got {point_kinds.shape}.")
  return point_kinds


def _build_render_index_map(instances, max_points_per_object, point_kinds):
  render_indices = {}
  for instance in instances:
    start, end = [int(x) for x in instance["point_range"]]
    full_indices = np.arange(start, end, dtype=np.int32)
    if max_points_per_object <= 0 or full_indices.size <= max_points_per_object:
      render_indices[instance["instance_index"]] = full_indices
      continue

    instance_point_kinds = point_kinds[start:end]
    surface_indices = full_indices[instance_point_kinds == POINT_KIND_SURFACE]
    volume_indices = full_indices[instance_point_kinds == POINT_KIND_VOLUME]
    if surface_indices.size >= max_points_per_object:
      selected = _subset_existing_indices(surface_indices, max_points_per_object)
    else:
      remaining = max_points_per_object - surface_indices.size
      volume_selected = _subset_existing_indices(volume_indices, remaining)
      selected = np.concatenate([surface_indices, volume_selected], axis=0)
    render_indices[instance["instance_index"]] = selected.astype(np.int32)
  return render_indices


def _compute_world_bounds(point_states, axes):
  coords = point_states[:, :, axes].reshape(-1, 2)
  minimum = coords.min(axis=0)
  maximum = coords.max(axis=0)
  span = np.maximum(maximum - minimum, 1e-3)
  padding = 0.08 * span + 1e-3
  return minimum - padding, maximum + padding


def _world_to_canvas(points, minimum, maximum, image_size, margin):
  width, height = image_size
  points = np.asarray(points, dtype=np.float32)
  span = np.maximum(maximum - minimum, 1e-6)
  usable_width = max(width - 2 * margin, 1)
  usable_height = max(height - 2 * margin, 1)
  normalized = (points - minimum) / span
  x = margin + normalized[:, 0] * usable_width
  y = height - margin - normalized[:, 1] * usable_height
  return np.stack([x, y], axis=-1)


def _draw_arrow(draw, start, end, color, width=2):
  start = np.asarray(start, dtype=np.float32)
  end = np.asarray(end, dtype=np.float32)
  draw.line((float(start[0]), float(start[1]), float(end[0]), float(end[1])),
            fill=color, width=width)
  direction = end - start
  length = float(np.linalg.norm(direction))
  if length < 1e-6:
    return
  direction /= length
  normal = np.array([-direction[1], direction[0]], dtype=np.float32)
  arrow_head = 6.0
  left = end - arrow_head * direction + 0.5 * arrow_head * normal
  right = end - arrow_head * direction - 0.5 * arrow_head * normal
  draw.polygon(
      [(float(end[0]), float(end[1])),
       (float(left[0]), float(left[1])),
       (float(right[0]), float(right[1]))],
      fill=color)


def _volume_point_color(color):
  color = np.asarray(color, dtype=np.float32)
  shaded = 0.55 * color + 0.10 * 255.0
  return tuple(np.clip(np.round(shaded), 0, 255).astype(np.uint8).tolist())


def _surface_point_color(color):
  return tuple(np.asarray(color, dtype=np.uint8).tolist())


def _get_depth_tolerance(reference_depth, args):
  return args.depth_tolerance_abs + args.depth_tolerance_rel * max(float(reference_depth), 1.0)


def _point_matches_visibility(
    segmentation,
    depth_map,
    pixel_x,
    pixel_y,
    instance_label,
    point_depth,
    args,
):
  height, width = segmentation.shape
  radius = max(int(args.visibility_radius), 0)
  x0 = max(pixel_x - radius, 0)
  x1 = min(pixel_x + radius + 1, width)
  y0 = max(pixel_y - radius, 0)
  y1 = min(pixel_y + radius + 1, height)

  segmentation_patch = segmentation[y0:y1, x0:x1]
  object_mask = segmentation_patch == instance_label
  if not np.any(object_mask):
    return False

  patch_depth = depth_map[y0:y1, x0:x1]
  visible_surface_depth = float(np.min(patch_depth[object_mask]))
  tolerance = _get_depth_tolerance(visible_surface_depth, args)
  return abs(float(point_depth) - visible_surface_depth) <= tolerance


def _compute_instance_projection(
    object_points,
    camera_position,
    camera_quaternion,
    intrinsics,
    segmentation,
    depth_map,
    instance_label,
    image_size,
    args,
):
  if instance_label <= 0 or len(object_points) == 0:
    empty = np.zeros((0,), dtype=bool)
    return empty, np.zeros((0, 2), dtype=np.int32)

  image_coords, depth_sign = _project_points(
      object_points, camera_position, camera_quaternion, intrinsics)
  projected_pixels = _normalized_to_pixel(image_coords, image_size)
  point_depths = np.linalg.norm(
      object_points - np.asarray(camera_position, dtype=np.float32)[None, :], axis=1)

  valid = (
      (depth_sign > 0)
      & (image_coords[:, 0] >= 0.0)
      & (image_coords[:, 0] <= 1.0)
      & (image_coords[:, 1] >= 0.0)
      & (image_coords[:, 1] <= 1.0)
  )
  filtered = np.zeros(len(object_points), dtype=bool)

  for point_index in np.flatnonzero(valid):
    pixel_x, pixel_y = projected_pixels[point_index]
    if _point_matches_visibility(
        segmentation=segmentation,
        depth_map=depth_map,
        pixel_x=int(pixel_x),
        pixel_y=int(pixel_y),
        instance_label=int(instance_label),
        point_depth=float(point_depths[point_index]),
        args=args):
      filtered[point_index] = True

  return filtered, projected_pixels


def _compute_frame_projection_data(
    frame_points,
    frame_velocities,
    instances,
    render_index_map,
    point_kinds,
    metadata,
    frame_index,
    input_dir,
    frame_id,
    args,
):
  del frame_velocities  # only frame_points are required for visibility filtering
  segmentation = _load_segmentation_image(input_dir, int(frame_id))
  depth_map = _load_depth_image(input_dir, int(frame_id))
  camera = metadata["camera"]
  intrinsics = np.asarray(camera["K"], dtype=np.float32)
  camera_position = np.asarray(camera["positions"], dtype=np.float32)[frame_index]
  camera_quaternion = np.asarray(camera["quaternions"], dtype=np.float32)[frame_index]
  image_size = (segmentation.shape[1], segmentation.shape[0])

  projection_data = {}
  for instance in instances:
    instance_index = int(instance["instance_index"])
    point_indices = render_index_map[instance_index]
    object_points = frame_points[point_indices]
    instance_label = int(instance.get("visible_instance_index", -1)) + 1
    visible_mask, projected_pixels = _compute_instance_projection(
        object_points=object_points,
        camera_position=camera_position,
        camera_quaternion=camera_quaternion,
        intrinsics=intrinsics,
        segmentation=segmentation,
        depth_map=depth_map,
        instance_label=instance_label,
        image_size=image_size,
        args=args)
    projection_data[instance_index] = {
        "render_indices": point_indices,
        "point_kinds": point_kinds[point_indices],
        "visible_mask": visible_mask,
        "projected_pixels": projected_pixels,
        "instance_label": instance_label,
    }
  return projection_data


def _write_point_cloud_ply(path, vertices, colors):
  vertices = np.asarray(vertices, dtype=np.float32)
  colors = np.asarray(colors, dtype=np.uint8)
  with path.open("w", encoding="utf-8") as fp:
    fp.write("ply\n")
    fp.write("format ascii 1.0\n")
    fp.write(f"element vertex {len(vertices)}\n")
    fp.write("property float x\n")
    fp.write("property float y\n")
    fp.write("property float z\n")
    fp.write("property uchar red\n")
    fp.write("property uchar green\n")
    fp.write("property uchar blue\n")
    fp.write("end_header\n")
    for vertex, color in zip(vertices, colors):
      fp.write(
          f"{float(vertex[0]):.7f} {float(vertex[1]):.7f} {float(vertex[2]):.7f} "
          f"{int(color[0])} {int(color[1])} {int(color[2])}\n")


def _write_mesh_ply(path, vertices, faces, colors):
  vertices = np.asarray(vertices, dtype=np.float32)
  faces = np.asarray(faces, dtype=np.int32)
  colors = np.asarray(colors, dtype=np.uint8)
  with path.open("w", encoding="utf-8") as fp:
    fp.write("ply\n")
    fp.write("format ascii 1.0\n")
    fp.write(f"element vertex {len(vertices)}\n")
    fp.write("property float x\n")
    fp.write("property float y\n")
    fp.write("property float z\n")
    fp.write("property uchar red\n")
    fp.write("property uchar green\n")
    fp.write("property uchar blue\n")
    fp.write(f"element face {len(faces)}\n")
    fp.write("property list uchar int vertex_indices\n")
    fp.write("end_header\n")
    for vertex, color in zip(vertices, colors):
      fp.write(
          f"{float(vertex[0]):.7f} {float(vertex[1]):.7f} {float(vertex[2]):.7f} "
          f"{int(color[0])} {int(color[1])} {int(color[2])}\n")
    for face in faces:
      fp.write(f"3 {int(face[0])} {int(face[1])} {int(face[2])}\n")


def _write_combined_mesh_points_ply(
    path,
    mesh_vertices,
    mesh_faces,
    mesh_colors,
    point_vertices,
    point_colors,
):
  mesh_vertices = np.asarray(mesh_vertices, dtype=np.float32)
  mesh_faces = np.asarray(mesh_faces, dtype=np.int32)
  mesh_colors = np.asarray(mesh_colors, dtype=np.uint8)
  point_vertices = np.asarray(point_vertices, dtype=np.float32)
  point_colors = np.asarray(point_colors, dtype=np.uint8)

  all_vertices = np.concatenate([mesh_vertices, point_vertices], axis=0)
  all_colors = np.concatenate([mesh_colors, point_colors], axis=0)

  with path.open("w", encoding="utf-8") as fp:
    fp.write("ply\n")
    fp.write("format ascii 1.0\n")
    fp.write(f"element vertex {len(all_vertices)}\n")
    fp.write("property float x\n")
    fp.write("property float y\n")
    fp.write("property float z\n")
    fp.write("property uchar red\n")
    fp.write("property uchar green\n")
    fp.write("property uchar blue\n")
    fp.write(f"element face {len(mesh_faces)}\n")
    fp.write("property list uchar int vertex_indices\n")
    fp.write("end_header\n")
    for vertex, color in zip(all_vertices, all_colors):
      fp.write(
          f"{float(vertex[0]):.7f} {float(vertex[1]):.7f} {float(vertex[2]):.7f} "
          f"{int(color[0])} {int(color[1])} {int(color[2])}\n")
    for face in mesh_faces:
      fp.write(f"3 {int(face[0])} {int(face[1])} {int(face[2])}\n")


def _soften_mesh_colors(colors):
  colors = np.asarray(colors, dtype=np.float32)
  softened = 0.45 * colors + 0.55 * 255.0
  return np.clip(np.round(softened), 0, 255).astype(np.uint8)


def _estimate_rigid_transform(local_points, world_points):
  local_points = np.asarray(local_points, dtype=np.float32)
  world_points = np.asarray(world_points, dtype=np.float32)
  if len(local_points) == 0:
    return np.eye(3, dtype=np.float32), np.zeros((3,), dtype=np.float32)
  if len(local_points) == 1:
    translation = world_points[0] - local_points[0]
    return np.eye(3, dtype=np.float32), translation.astype(np.float32)

  local_center = local_points.mean(axis=0)
  world_center = world_points.mean(axis=0)
  local_centered = local_points - local_center
  world_centered = world_points - world_center
  covariance = local_centered.T @ world_centered
  u_matrix, _, vt_matrix = np.linalg.svd(covariance)
  rotation = u_matrix @ vt_matrix
  if np.linalg.det(rotation) < 0:
    correction = np.eye(3, dtype=np.float32)
    correction[-1, -1] = -1.0
    rotation = u_matrix @ correction @ vt_matrix
  translation = world_center - local_center @ rotation
  return rotation.astype(np.float32), translation.astype(np.float32)


def _export_frame_3d_assets(
    output_dir,
    frame_id,
    frame_points,
    instances,
    render_index_map,
    projection_data,
    point_payload,
    point_kinds,
    palette,
):
  point_dir = output_dir / "point_clouds"
  mesh_dir = output_dir / "meshes"
  combined_dir = output_dir / "combined"
  point_dir.mkdir(parents=True, exist_ok=True)
  mesh_dir.mkdir(parents=True, exist_ok=True)
  combined_dir.mkdir(parents=True, exist_ok=True)

  all_point_vertices = []
  all_point_colors = []
  visible_point_vertices = []
  visible_point_colors = []
  mesh_vertices = []
  mesh_faces = []
  mesh_colors = []
  mesh_vertex_offset = 0
  local_points_all = np.asarray(point_payload["local_points"], dtype=np.float32)

  for instance in instances:
    instance_index = int(instance["instance_index"])
    color = np.asarray(palette[instance_index], dtype=np.uint8)
    start, end = [int(x) for x in instance["point_range"]]
    full_indices = np.arange(start, end, dtype=np.int32)
    if full_indices.size == 0:
      continue

    object_world_points = frame_points[full_indices]
    all_point_vertices.append(object_world_points)
    object_point_kinds = point_kinds[full_indices]
    object_point_colors = np.tile(np.asarray(_volume_point_color(color), dtype=np.uint8)[None, :],
                                  (len(object_world_points), 1))
    object_point_colors[object_point_kinds == POINT_KIND_SURFACE] = np.asarray(
        _surface_point_color(color), dtype=np.uint8)
    all_point_colors.append(object_point_colors)

    render_indices = render_index_map[instance_index]
    visible_mask = projection_data[instance_index]["visible_mask"]
    if np.any(visible_mask):
      visible_points = frame_points[render_indices][visible_mask]
      render_point_kinds = projection_data[instance_index]["point_kinds"][visible_mask]
      visible_colors = np.tile(
          np.asarray(_volume_point_color(color), dtype=np.uint8)[None, :],
          (len(visible_points), 1))
      visible_colors[render_point_kinds == POINT_KIND_SURFACE] = np.asarray(
          _surface_point_color(color), dtype=np.uint8)
      visible_point_vertices.append(visible_points)
      visible_point_colors.append(visible_colors)

    object_mesh_vertices = instance.get("mesh_vertices_local")
    object_mesh_faces = instance.get("mesh_faces")
    if object_mesh_vertices is None or object_mesh_faces is None:
      continue

    local_points = local_points_all[full_indices]
    rotation, translation = _estimate_rigid_transform(local_points, object_world_points)
    world_mesh_vertices = np.asarray(object_mesh_vertices, dtype=np.float32) @ rotation + translation
    object_mesh_faces = np.asarray(object_mesh_faces, dtype=np.int32)

    mesh_vertices.append(world_mesh_vertices)
    mesh_faces.append(object_mesh_faces + mesh_vertex_offset)
    mesh_colors.append(np.tile(color[None, :], (len(world_mesh_vertices), 1)))
    mesh_vertex_offset += len(world_mesh_vertices)

  if all_point_vertices:
    all_points = np.concatenate(all_point_vertices, axis=0)
    all_colors = np.concatenate(all_point_colors, axis=0)
    _write_point_cloud_ply(
        point_dir / f"frame_{frame_id:05d}_points_world.ply",
        all_points, all_colors)

  if visible_point_vertices:
    visible_points = np.concatenate(visible_point_vertices, axis=0)
    visible_colors = np.concatenate(visible_point_colors, axis=0)
    _write_point_cloud_ply(
        point_dir / f"frame_{frame_id:05d}_points_visible_subset.ply",
        visible_points, visible_colors)

  if mesh_vertices:
    combined_vertices = np.concatenate(mesh_vertices, axis=0)
    combined_faces = np.concatenate(mesh_faces, axis=0)
    combined_colors = np.concatenate(mesh_colors, axis=0)
    _write_mesh_ply(
        mesh_dir / f"frame_{frame_id:05d}_mesh_world.ply",
        combined_vertices, combined_faces, combined_colors)

    softened_mesh_colors = _soften_mesh_colors(combined_colors)
    if all_point_vertices:
      _write_combined_mesh_points_ply(
          combined_dir / f"frame_{frame_id:05d}_mesh_and_points_world.ply",
          combined_vertices,
          combined_faces,
          softened_mesh_colors,
          all_points,
          all_colors)
    if visible_point_vertices:
      _write_combined_mesh_points_ply(
          combined_dir / f"frame_{frame_id:05d}_mesh_and_points_visible_subset.ply",
          combined_vertices,
          combined_faces,
          softened_mesh_colors,
          visible_points,
          visible_colors)


def _render_projection_panel(
    input_dir,
    frame_index,
    frame_id,
    frame_points,
    frame_velocities,
    instances,
    render_index_map,
    projection_data,
    palette,
    metadata,
    args,
):
  scene_metadata = metadata["metadata"]
  camera = metadata["camera"]
  image = _load_rgba_image(input_dir, int(frame_id), scene_metadata["resolution"])
  overlay = Image.new("RGBA", image.size, (0, 0, 0, 0))
  draw = ImageDraw.Draw(overlay)
  intrinsics = np.asarray(camera["K"], dtype=np.float32)
  camera_position = np.asarray(camera["positions"], dtype=np.float32)[frame_index]
  camera_quaternion = np.asarray(camera["quaternions"], dtype=np.float32)[frame_index]

  for instance in instances:
    instance_index = int(instance["instance_index"])
    color = palette[instance_index]
    selected = render_index_map[instance_index]
    if selected.size == 0:
      continue

    object_points = frame_points[selected]
    object_velocities = frame_velocities[selected]
    object_point_kinds = projection_data[instance_index]["point_kinds"]
    filtered = projection_data[instance_index]["visible_mask"]
    projected_pixels = projection_data[instance_index]["projected_pixels"]
    if not np.any(filtered):
      continue

    pixels = projected_pixels[filtered]
    visible_point_kinds = object_point_kinds[filtered]
    surface_pixels = pixels[visible_point_kinds == POINT_KIND_SURFACE]
    volume_pixels = pixels[visible_point_kinds == POINT_KIND_VOLUME]

    for x, y in volume_pixels:
      volume_color = _volume_point_color(color)
      draw.ellipse(
          (x - max(args.point_radius - 1, 1), y - max(args.point_radius - 1, 1),
           x + max(args.point_radius - 1, 1), y + max(args.point_radius - 1, 1)),
          fill=volume_color + (90,),
          outline=(0, 0, 0, 90))
    for x, y in surface_pixels:
      surface_color = _surface_point_color(color)
      draw.ellipse(
          (x - args.point_radius, y - args.point_radius,
           x + args.point_radius, y + args.point_radius),
          fill=surface_color + (180,),
          outline=(0, 0, 0, 160))

    visible_points = object_points[filtered]
    visible_velocities = object_velocities[filtered]
    if surface_pixels.shape[0] > 0:
      centroid_pixel = np.mean(surface_pixels.astype(np.float32), axis=0)
      surface_visible_points = visible_points[visible_point_kinds == POINT_KIND_SURFACE]
      surface_visible_velocities = visible_velocities[visible_point_kinds == POINT_KIND_SURFACE]
      mean_velocity = surface_visible_velocities.mean(axis=0)
      centroid_world = surface_visible_points.mean(axis=0, keepdims=True)
    else:
      centroid_pixel = np.mean(pixels.astype(np.float32), axis=0)
      mean_velocity = visible_velocities.mean(axis=0)
      centroid_world = visible_points.mean(axis=0, keepdims=True)
    future_world = centroid_world + args.velocity_scale * mean_velocity[None, :]
    future_coords, future_depth = _project_points(
        future_world, camera_position, camera_quaternion, intrinsics)
    if (
        future_depth[0] > 0
        and 0.0 <= future_coords[0, 0] <= 1.0
        and 0.0 <= future_coords[0, 1] <= 1.0
    ):
      future_pixel = _normalized_to_pixel(future_coords, image.size)[0]
      _draw_arrow(draw, centroid_pixel, future_pixel, color=color + (255,), width=2)
    draw.text(
        (float(centroid_pixel[0] + 4), float(centroid_pixel[1] - 10)),
        str(instance_index),
        fill=color + (255,),
        font=ImageFont.load_default())

  panel = Image.alpha_composite(image, overlay).convert("RGB")
  header = Image.new("RGB", (panel.width, 24), (245, 245, 245))
  ImageDraw.Draw(header).text(
      (8, 6),
      f"Projected Points on RGBA | frame {frame_id:04d}",
      fill=(20, 20, 20),
      font=ImageFont.load_default())
  merged = Image.new("RGB", (panel.width, panel.height + header.height), (255, 255, 255))
  merged.paste(header, (0, 0))
  merged.paste(panel, (0, header.height))
  return merged


def _render_world_panel(
    frame_points,
    frame_velocities,
    instances,
    render_index_map,
    point_kinds,
    palette,
    axes,
    bounds,
    size,
    title,
    velocity_scale,
):
  axis_indices = np.asarray(axes, dtype=np.int32)
  margin = 24
  panel = Image.new("RGB", (size, size + 24), (255, 255, 255))
  draw = ImageDraw.Draw(panel)
  draw.text((8, 6), title, fill=(20, 20, 20), font=ImageFont.load_default())

  plot_origin_y = 24
  plot_size = (size, size)
  plot_box = (0, plot_origin_y, size, plot_origin_y + size)
  draw.rectangle(plot_box, outline=(180, 180, 180), width=1)

  minimum, maximum = bounds
  for instance in instances:
    instance_index = int(instance["instance_index"])
    color = palette[instance_index]
    selected = render_index_map[instance_index]
    if selected.size == 0:
      continue

    points2d = frame_points[selected][:, axes]
    selected_point_kinds = point_kinds[selected]
    pixels = _world_to_canvas(
        points2d, minimum, maximum, plot_size, margin)
    pixels[:, 1] += plot_origin_y
    volume_pixels = pixels[selected_point_kinds == POINT_KIND_VOLUME]
    surface_pixels = pixels[selected_point_kinds == POINT_KIND_SURFACE]
    volume_color = _volume_point_color(color)
    surface_color = _surface_point_color(color)
    for x, y in volume_pixels:
      draw.ellipse((x - 1, y - 1, x + 1, y + 1), fill=volume_color, outline=(0, 0, 0))
    for x, y in surface_pixels:
      draw.ellipse((x - 2, y - 2, x + 2, y + 2), fill=surface_color, outline=(0, 0, 0))

    centroid = frame_points[selected].mean(axis=0)
    mean_velocity = frame_velocities[selected].mean(axis=0)
    arrow_points = np.stack([
        centroid[axis_indices],
        centroid[axis_indices] + velocity_scale * mean_velocity[axis_indices],
    ], axis=0)
    arrow_pixels = _world_to_canvas(
        arrow_points, minimum, maximum, plot_size, margin)
    arrow_pixels[:, 1] += plot_origin_y
    _draw_arrow(draw, arrow_pixels[0], arrow_pixels[1], color=color, width=2)
    draw.text(
        (float(arrow_pixels[0][0] + 4), float(arrow_pixels[0][1] - 10)),
        str(instance_index),
        fill=color,
        font=ImageFont.load_default())

  return panel


def _render_summary_panel(frame_id, point_states, instances, width):
  speeds = np.linalg.norm(point_states[:, 3:], axis=-1)
  total_points = int(point_states.shape[0])
  lines = [
      f"Frame {frame_id:04d}",
      f"Points: {total_points}",
      f"Speed mean/max: {speeds.mean():.3f} / {speeds.max():.3f}",
      f"Objects: {len(instances)}",
  ]
  for instance in instances:
    start, end = instance["point_range"]
    object_speeds = np.linalg.norm(point_states[start:end, 3:], axis=-1)
    lines.append(
        f"[{instance['instance_index']}] {instance.get('asset_id') or instance['name']}: "
        f"points={end - start} "
        f"(surface={instance.get('num_surface_points', 0)}, "
        f"volume={instance.get('num_volume_points', end - start)}) "
        f"speed={object_speeds.mean():.3f}")

  panel_height = 16 + 16 * len(lines)
  panel = Image.new("RGB", (width, panel_height), (248, 248, 248))
  draw = ImageDraw.Draw(panel)
  for row_index, line in enumerate(lines):
    draw.text((8, 4 + 16 * row_index), line, fill=(20, 20, 20), font=ImageFont.load_default())
  return panel


def _stack_frame_panels(projection_panel, xy_panel, xz_panel, summary_panel):
  gap = 8
  top_height = max(projection_panel.height, xy_panel.height, xz_panel.height)
  total_width = projection_panel.width + xy_panel.width + xz_panel.width + 4 * gap
  total_height = top_height + summary_panel.height + 3 * gap
  canvas = Image.new("RGB", (total_width, total_height), (255, 255, 255))

  x = gap
  y = gap
  canvas.paste(projection_panel, (x, y))
  x += projection_panel.width + gap
  canvas.paste(xy_panel, (x, y))
  x += xy_panel.width + gap
  canvas.paste(xz_panel, (x, y))
  canvas.paste(summary_panel, (gap, top_height + 2 * gap))
  return canvas


def _validate_payload(metadata, point_payload):
  if "point_states" not in point_payload:
    raise KeyError("point_cloud_states.pkl does not contain 'point_states'.")
  if "instances" not in point_payload:
    raise KeyError("point_cloud_states.pkl does not contain 'instances'.")

  point_states = np.asarray(point_payload["point_states"], dtype=np.float32)
  if point_states.ndim != 3 or point_states.shape[-1] != 6:
    raise ValueError(
        f"Expected point_states with shape (T, N, 6), got {point_states.shape}.")

  instances = point_payload["instances"]
  if not isinstance(instances, list):
    raise TypeError("Expected 'instances' to be a list.")

  total_points = sum(int(instance["point_range"][1]) - int(instance["point_range"][0])
                     for instance in instances)
  if total_points != point_states.shape[1]:
    raise ValueError(
        f"Sum of point ranges ({total_points}) does not match point_states.shape[1] "
        f"({point_states.shape[1]}).")

  frame_ids = np.asarray(point_payload.get("frame_ids"), dtype=np.int32)
  if frame_ids.shape[0] != point_states.shape[0]:
    raise ValueError(
        f"frame_ids length ({frame_ids.shape[0]}) does not match point_states.shape[0] "
        f"({point_states.shape[0]}).")

  point_summary = metadata.get("point_cloud_states")
  if point_summary is not None:
    expected_shape = tuple(int(x) for x in point_summary.get("shape", ()))
    if expected_shape and expected_shape != tuple(point_states.shape):
      raise ValueError(
          f"metadata.json reports shape {expected_shape}, but payload shape is "
          f"{tuple(point_states.shape)}.")

  _get_point_kinds(point_payload, point_states.shape[1])


def _write_summary(input_dir, output_dir, point_payload):
  point_states = np.asarray(point_payload["point_states"], dtype=np.float32)
  instances = point_payload["instances"]
  frame_ids = np.asarray(point_payload["frame_ids"], dtype=np.int32)
  speeds = np.linalg.norm(point_states[:, :, 3:], axis=-1)

  lines = [
      f"input_dir: {input_dir}",
      f"frames: {point_states.shape[0]}",
      f"frame_ids: {frame_ids[0]}..{frame_ids[-1]}",
      f"points_total: {point_states.shape[1]}",
      f"state_shape: {tuple(point_states.shape)}",
      f"speed_mean: {float(speeds.mean()):.6f}",
      f"speed_max: {float(speeds.max()):.6f}",
      f"objects: {len(instances)}",
      "",
      "per_object:",
  ]

  for instance in instances:
    start, end = [int(x) for x in instance["point_range"]]
    object_speeds = np.linalg.norm(point_states[:, start:end, 3:], axis=-1)
    lines.append(
        f"  [{instance['instance_index']}] "
        f"asset_id={instance.get('asset_id')} "
        f"name={instance.get('name')} "
        f"strategy={instance.get('point_count_strategy', 'fixed')} "
        f"points={end - start} "
        f"surface_points={instance.get('num_surface_points', 0)} "
        f"volume_points={instance.get('num_volume_points', end - start)} "
        f"surface_area={float(instance.get('surface_area', 0.0)):.6f} "
        f"volume={float(instance.get('volume', 0.0)):.6f} "
        f"range=({start}, {end}) "
        f"visible_index={instance.get('visible_instance_index', -1)} "
        f"measure_methods=("
        f"{instance.get('surface_measure_method', 'unknown')},"
        f"{instance.get('volume_measure_method', 'unknown')}) "
        f"sampling={instance.get('sampling_method')} "
        f"speed_mean={float(object_speeds.mean()):.6f} "
        f"speed_max={float(object_speeds.max()):.6f}")

  summary_path = output_dir / "summary.txt"
  summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
  print("\n".join(lines))


def main():
  args = parse_args()
  output_dir = _resolve_output_dir(args)
  frames_dir = output_dir / "frames"
  frames_dir.mkdir(parents=True, exist_ok=True)

  metadata_path = args.input_dir / "metadata.json"
  _require_file(metadata_path, f"Missing {metadata_path}.")
  metadata = _load_json(metadata_path)

  point_state_path = _find_point_state_path(args.input_dir, metadata)
  point_payload = _load_pickle(point_state_path)
  _validate_payload(metadata, point_payload)

  point_states = np.asarray(point_payload["point_states"], dtype=np.float32)
  frame_ids = np.asarray(point_payload["frame_ids"], dtype=np.int32)
  point_kinds = _get_point_kinds(point_payload, point_states.shape[1])
  instances = point_payload["instances"]
  palette = _get_palette(len(instances))
  render_index_map = _build_render_index_map(instances, args.max_points_per_object, point_kinds)

  xy_bounds = _compute_world_bounds(point_states[:, :, :3], axes=(0, 1))
  xz_bounds = _compute_world_bounds(point_states[:, :, :3], axes=(0, 2))

  summary_path = output_dir / "summary.txt"
  if summary_path.exists():
    summary_path.unlink()
  _write_summary(args.input_dir, output_dir, point_payload)

  saved_frames = []
  frame_indices = list(range(0, len(frame_ids), max(args.frame_stride, 1)))
  # print(len(frame_ids), frame_ids)
  frame_rate = float(metadata["metadata"]["frame_rate"])

  for frame_index in frame_indices:
    frame_id = int(frame_ids[frame_index])
    frame_points = point_states[frame_index, :, :3]
    frame_velocities = point_states[frame_index, :, 3:]
    projection_data = _compute_frame_projection_data(
        frame_points=frame_points,
        frame_velocities=frame_velocities,
        instances=instances,
        render_index_map=render_index_map,
        point_kinds=point_kinds,
        metadata=metadata,
        frame_index=frame_index,
        input_dir=args.input_dir,
        frame_id=frame_id,
        args=args)

    projection_panel = _render_projection_panel(
        input_dir=args.input_dir,
        frame_index=frame_index,
        frame_id=frame_id,
        frame_points=frame_points,
        frame_velocities=frame_velocities,
        instances=instances,
        render_index_map=render_index_map,
        projection_data=projection_data,
        palette=palette,
        metadata=metadata,
        args=args)
    xy_panel = _render_world_panel(
        frame_points=frame_points,
        frame_velocities=frame_velocities,
        instances=instances,
        render_index_map=render_index_map,
        point_kinds=point_kinds,
        palette=palette,
        axes=(0, 1),
        bounds=xy_bounds,
        size=args.world_view_size,
        title="Bird's-eye View (X/Y)",
        velocity_scale=args.velocity_scale)
    xz_panel = _render_world_panel(
        frame_points=frame_points,
        frame_velocities=frame_velocities,
        instances=instances,
        render_index_map=render_index_map,
        point_kinds=point_kinds,
        palette=palette,
        axes=(0, 2),
        bounds=xz_bounds,
        size=args.world_view_size,
        title="Side View (X/Z)",
        velocity_scale=args.velocity_scale)
    summary_panel = _render_summary_panel(
        frame_id=frame_id,
        point_states=point_states[frame_index],
        instances=instances,
        width=projection_panel.width + xy_panel.width + xz_panel.width + 24)

    canvas = _stack_frame_panels(
        projection_panel=projection_panel,
        xy_panel=xy_panel,
        xz_panel=xz_panel,
        summary_panel=summary_panel)
    frame_path = frames_dir / f"frame_{frame_id:05d}.png"
    canvas.save(frame_path)
    saved_frames.append(frame_path)

    if not args.skip_3d_export:
      _export_frame_3d_assets(
          output_dir=output_dir,
          frame_id=frame_id,
          frame_points=frame_points,
          instances=instances,
          render_index_map=render_index_map,
          projection_data=projection_data,
          point_payload=point_payload,
          point_kinds=point_kinds,
          palette=palette)

  if saved_frames and not args.skip_gif:
    gif_path = output_dir / args.gif_name
    images = [Image.open(saved_frames[0]).convert("P", palette=Image.ADAPTIVE)]
    appended = [
        Image.open(frame_path).convert("P", palette=Image.ADAPTIVE)
        for frame_path in saved_frames[1:]
    ]
    frame_duration_ms = max(int(round(1000.0 / frame_rate * max(args.frame_stride, 1))), 1)
    images[0].save(
        gif_path,
        save_all=True,
        append_images=appended,
        duration=frame_duration_ms,
        loop=0)

  print(f"Wrote visualization to {output_dir}")


if __name__ == "__main__":
  main()
